### ISSUE TITLE
ゲームUI 

### ISSUE THREAD

**Issue by TetraMiyazaki** [jphacks/FK_1904#2]
担当：こーた

**Comment by kpasso1015** [comment]
![Uploading Screen Shot 2019-10-19 at 15.57.02.png…]()

**Comment by TetraMiyazaki** [comment]
<img width="1034" alt="Screen Shot 2019-10-19 at 15 57 02" src="https://user-images.githubusercontent.com/12492226/67139277-498e1380-f289-11e9-997d-bee1cc75ae33.png">
